{"name": "test_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 3", "trace": "def test_3():\n>       assert 1==3\nE       assert 1 == 3\n\ntest_case_01.py:9: AssertionError"}, "start": 1608626488554, "stop": 1608626488554, "uuid": "31669419-2e06-4b92-96fa-c6186bfaefd5", "historyId": "1f464fb9d44e743cf89a51f38d63a83f", "testCaseId": "5c1c497814f50e67b8e3477d6f1c2b5f", "fullName": "test_case_01#test_3", "labels": [{"name": "suite", "value": "test_case_01"}, {"name": "host", "value": "LAPTOP-T9T0JTJ0"}, {"name": "thread", "value": "2636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case_01"}]}